baseurl:        /
auto:           true

markdown:       redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:       true
paginate:       30
paginate_path:  "index/page:num"
permalink:      /posts/:title/

title:          "Yet Another Summer Rain"

exclude:        ['README.md']

gems:           ['jekyll-paginate', 'jekyll-multiple-languages']

host_name:      'www.liaohuqiu.net'

author:         liaohuqiu@gmail.com 廖祜秋
s_host:         'http://srain-blog.qiniudn.com'
# s_host:         ''

# -----------------

# Multiple languages
languages:          ['en', 'cn']

# If not config, the first of languages will be the default
language_default:   "en"

# If a post of default language not set `no_fill_default_content` to true
# Its content will use to replace if the corresponding content of other languages is not exist.
# 
fill_default_content: false

# -----------------
